package com.banking.enums;
public enum TransactionType {
    DEPOSIT, WITHDRAWAL, TRANSFER_IN, TRANSFER_OUT,
    LOAN_DISBURSEMENT, LOAN_REPAYMENT, INTEREST_CREDIT,
    FD_CREATION, FD_MATURITY, REVERSAL, CHARGE, REFUND
}
